### ISSUE TITLE
QA | A11y

### ISSUE THREAD

**Issue by EnriqueOrt** [GSA/px-benefit-finder#1220]
### Domain

a11y

### Related Issue(s)

New issues that arise from this task should be created using the [Bug Report form](https://github.com/GSA/px-benefit-finder/issues/new?assignees=&labels=bug&projects=&template=bug_report_form.yml).

[Heading Levels order invalid on Error Stat](https://github.com/GSA/px-benefit-finder/issues/1072)	https://github.com/GSA/px-benefit-finder/issues/1072
[Elements must only use supported aria-attributes](https://github.com/GSA/px-benefit-finder/issues/1073)	https://github.com/GSA/px-benefit-finder/issues/1073
[Modal Missing H1](https://github.com/GSA/px-benefit-finder/issues/1119)	https://github.com/GSA/px-benefit-finder/issues/1119
[Info alerts in accordions are hidden to AT](https://github.com/GSA/px-benefit-finder/issues/1183)	https://github.com/GSA/px-benefit-finder/issues/1183

### Description

**Accessibility final QA for a11y related updates**

**Comment by scottqueen-bixal** [comment]
@angelina-smith I wanted to add this issue  to your QA review, since it is a new component I want to make sure we get your eyes on it for a11y before it goes out.

https://github.com/GSA/px-benefit-finder/issues/1196

Let me know if you have any questions or concerns

Should be available for review on storybook, 

https://benefit-finder-storybook-dev.app.cloud.gov/iframe.html?args=&id=app--primary&viewMode=story&?applicant_date_of_birth={%22month%22:%220%22,%22day%22:%2222%22,%22year%22:%222022%22}&applicant_relationship_to_the_deceased=Parent&applicant_marital_status=Married&applicant_citizen_status=Yes&applicant_care_for_child=Yes&applicant_paid_funeral_expenses=Yes&deceased_date_of_death={%22month%22:%221%22,%22year%22:%222022%22,%22day%22:%2222%22}&deceased_death_location_is_US=Yes&deceased_paid_into_SS=Yes&deceased_public_safety_officer=Yes&deceased_miner=Yes&deceased_american_indian=Yes&deceased_died_of_COVID=Yes&deceased_served_in_active_military=Yes&deceased_service_status=Discharged%20under%20conditions%20other%20than%20dishonorable&deceased_military_death_circumstance=Died%20while%20on%20inactive-duty%20training&deceased_grave_headstone=Yes&shared=true

**Comment by angelina-smith** [comment]
@scottqueen-bixal Reviewed the Summary Box component in [QA | Summary Component #1234](https://github.com/GSA/px-benefit-finder/issues/1234) and added my comments there. (TL;DR it sounds good in Storybook, just need Ernesto to confirm heading level of the 'Important' in the summary box)

Will review the other QA items by EOD to make sure I don't have any questions for you Scott!

**Comment by angelina-smith** [comment]
@scottqueen-bixal @fongcindy  Completed the a11y QA of the following items on Storybook (using ANDI and axeDevTools) , all items look good!

- https://github.com/GSA/px-benefit-finder/issues/1072 
- https://github.com/GSA/px-benefit-finder/issues/1073 
- https://github.com/GSA/px-benefit-finder/issues/1119 
- https://github.com/GSA/px-benefit-finder/issues/1183 (Info alerts have been removed within benefit accordions and replaced by the Summary Box component, so re-confirmed info alerts are not there)
