### ISSUE TITLE
Multiple benefits with same title

### ISSUE THREAD

**Issue by gchi25** [GSA/px-benefit-finder#1415]
### User / Persona

As content edit, I need to create multiple benefits with same title.

### Reason / Justification

[Accordion not opening in DOLO benefits](https://github.com/GSA/px-benefit-finder/issues/1410)
Have 2 benefits with same title. The accordions do not open as expected.

@diegocob: Is this something to avoid in the future? Some benefits may have the same name but have different eligibility criteria, life events and description.

Add benefit_id field in benefit content type to uniquely identify different benefits with same title.
Update React to get benefit by benefit_id.

### Acceptance Criteria (AC)

- [ ] Content editor creates multiple benefits with same title.
- [ ] React program opens their accordions as expected.

**Comment by diegocob** [comment]
As per our chat convo, I am not sure we need this now Gene. I suggested it bc we don't have a logic for the eligibility criteria that works with multiple conflicting criteria. 

For example, Section 8 ticket voucher is for people that have low income AND are >65 years OR have a disability. 

With the current logic I would have to create two benefits with the same name, one for people >65 years and one for disability. However, people filling out the form would see both benefits in the eligible or not-eligible results.

If someone meets both criteria, they would see the same benefit twice in their results.

**Comment by gchi25** [comment]
In current benefit data structure, you need to have 2 benefits as:

Section 8 ticket voucher
low income
>65

Section 8 ticket voucher
low income
disability

But you can not have benefit like:

Section 8 ticket voucher
low income
>65 OR disability

**Comment by diegocob** [comment]
That's right, Gene.

**Comment by fongcindy** [comment]
Gene, Scott, Diego, and Cindy to sync on this before deep dive of this work

**Comment by gchi25** [comment]
Add conditions logic OR in benefit eligibility criteria.
"benefit": {
    "title": "Housing choice voucher (Section 8)",
    "summary": "Learn if you are eligible for a Section 8 housing choice voucher to ...",
    "SourceLink": "https:\/\/www.usa.gov\/housing-voucher-section-8",
    "SourceIsEnglish": false,
    "agency": {
        "title": "Department of Housing and Urban Development (HUD)",
        "summary": "Administers programs that provide housing and community development assistance ...",
        "lede": ""
    },
    "eligibility": [
        {
            "criteriaKey": "applicant_income",
            "label": "The applicant has limited income and resources",
            "acceptableValues": [
                "Yes"
            ]
        },
        {
            "criteriaKey": "applicant_citizen_status",
            "label": "The applicant is a U.S. citizen or eligible non-citizen",
            "acceptableValues": [
                "Yes"
            ]
        }
		{
  			"conditions": [
        		{
            		"criteriaKey": "applicant_date_of_birth",
            		"label": "The applicant is at least 65 years old",
            		"acceptableValues": [
                		">65"
            		]
        		},
        		{
            		"criteriaKey": "applicant_disability",
            		"label": "The applicant has disability",
            		"acceptableValues": [
                		"Yes"
            		]
        		}   
  			],
  			"logic": "OR"
		}             
    ]
}

**Comment by scottqueen-bixal** [comment]
resurfacing this conversation here since it is related:

G. Scott Queen (USA.gov Contractor)
  2 months ago
@Diego Cob
 we do not have an "OR"option,
current mapping
### Use cases for label mapping
requirement | label/grouping
-- | --
user has met all criteria | Likely Eligible
user has met all but one criteria, which is undefined | More Information Needed
user has undefined all criteria | More Information Needed
user has unmet all criteria | Not Eligible
user has met all but one criteria, which is unmet | Not Eligible
user has unmet one criteria | Not Eligible


G. Scott Queen (USA.gov Contractor)
  [2 months ago](https://gsa-tts.slack.com/archives/C04DDBFQQTZ/p1716216213016919?thread_ts=1715978926.890089&cid=C04DDBFQQTZ)

Might be that the use case you are looking for isn't OR - but ANY,
user has met any of the criteria | Likely eligible


Diego Cob
  2 months ago
Will look into other benefits to see if we need to chat about finding a way to add to the logic.
I was thinking of having criteria that is required and another which if any of a set are met then they would be eligible.

For example, you need to meet A (US citizen) and any of the following B, C, or D (low income, have a disability or >64years)
The ANY could also be an option. This would help reduce some duplicate benefits but don't think it's super common.


G. Scott Queen (USA.gov Contractor)
  [2 months ago](https://gsa-tts.slack.com/archives/C04DDBFQQTZ/p1716217439469409?thread_ts=1715978926.890089&cid=C04DDBFQQTZ)
> For example, you need to meet A (US citizen) and any of the following B, C, or D (low income, have a disability or >64years)

This is different than what you originally described. It's an AND ANY.  We do this in a way already with the acceptable values field,  but in the use case you are describing the values are other criteria eligibility.

We would still need the ANY but also require some sort of parent:child relationship to the other entities.
This more complex, much bigger lift.


Diego Cob
  [2 months ago](https://gsa-tts.slack.com/archives/C04DDBFQQTZ/p1716220070916109?thread_ts=1715978926.890089&cid=C04DDBFQQTZ)
Ok. I'll put it in the backlog. There may be some work arounds to make it less of a lift but not sure still how relevant it will be for the short term.

because this is an AND_ANY it would likely look more like the following data structure

```JSON
          "eligibility": [
            {
              "criteriaKey": "low income",
              "label": "you are low income",
              "acceptableValues": ["low income", "low income"]
            },
            {
              "criteriaKey": "unassociated criteria",
              "label": "You meet one of the following; are older than 65, have a disability",
              "condition": "AND_ANY",
              "acceptableValues": [
                {
                  "criteriaKey": "age",
                  "label": "you are older than 65",
                  "acceptableValues": [">65"]
                },
                {
                  "criteriaKey": "disability",
                  "label": "you have a disability",
                  "acceptableValues": ["Yes"]
                }
              ]
            }
          ]
```

AC:
- [ ] if a a user does not meet _ANY_ of the unassociated criteria `acceptableValues` then the benefit is ineligible
- [ ] if a user meets _ANY_ of the unassociated criteria `acceptableValues` then the benefit continues to be eligible
- [ ] updated paragraph type logic for benefit paragraph type to handle associating the condition, and an array of acceptable criteria that come from multiple criteria key
- [ ] all error handling on the backend needs to handle this new structure

**Comment by scottqueen-bixal** [comment]
We will not implement this feature as it is only a bug that derived out of an unused implementation case on the content side, we have proposed the contextual conversation around supporting more complex eligibility scenarios here https://github.com/GSA/px-benefit-finder/issues/1570
