### ISSUE TITLE
Update pageView data layer variable to differentiate between form pages

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1477]
Update the pageView data layer attribute. See the attached excel spreadsheet for a list of proposed changes.

[Data Layer Variables PageView.xlsx](https://github.com/user-attachments/files/15959963/Data.Layer.Variables.PageView.xlsx)

By creating a variable that is language-agnostic and life experience-agnostic, it will simplify tracking and make things more stable to manage moving forward. It will also allow us to make meaningful data groupings and more efficiently analyze the user journey across life experiences and languages.

**Comment by scottqueen-bixal** [comment]
I don't want to move away from prefixing `bf` and aligning with the semantics of the application.

The way you have mapped the dataLayer value is not clear on how it resolves the requirement of `language-agnostic and life experience-agnostic` for those values

If we currently have a `dataLayer` object that looks like this;

```
  lifeEventSection: {
    event: 'bf_page_change',
    bfData: {
      pageView: 'bf-form',
      viewTitle: null,
    },
  },
```

The part that needs to be updated is `viewTitle`. We pull this value dynamically from the content itself.  IF our task in this issue is to make that more agnostic we would need to see mappings like the below,

| event | bfData.pageView |  bfData.viewTitle |
|-------------|----------|---|
| bf_page_change  | bf-form-{step number}  |  <form-id-{locale} > |


Everything should line up to our dataStructure in the application: you can find those values here `benefit-finder/src/shared/utils/dataLayerUtils/dataLayerStructure.js`

Let's continue to work on this.

**Comment by scottqueen-bixal** [comment]
will create a new ticket for ` and eligible and ineligible benefits` that includes

update on this object
```
  resultsView: {
    event: 'bf_page_change',
    bfData: {
      pageView: 'bf-result-view',
      viewTitle: null,
      viewState: [
        'bf-not-eligible-view',
        'bf-eligible-view',
        'bf-not-eligible-view-zero-benefits',
        'bf-eligible-view-zero-benefits',
      ],
    },
  },
```

so that `pageView: 'bf-result-view',` gets adjusted to append `not-eligible-view` and `eligible-view`
