### ISSUE TITLE
Update accordion open data layer event names

### ISSUE THREAD

**Issue by nickpistone** [GSA/px-benefit-finder#1516]
### Description

Change benefit-click to benefit-accordion-open

### Acceptance Criteria

When users click top open an accordion, the data layer event that fires will be called "bf-accordion-open"
Accordion open event will only fire when the accordion is opened, not when it is closed
Accordion open event will fire on both eligible and ineligible results pages

**Comment by scottqueen-bixal** [comment]
posting here for clarification

[10:50 AM] Scott Queen
Nick trying to confirm some of the AC on this ticket https://github.com/orgs/GSA/projects/48/views/10?filterQuery=-no%3Asprint+assignee%3A%40me&pane=issue&itemId=69180792
[10:51 AM] Scott Queen
right now you are requesting only for the updated event name for opening the accordion 
[10:51 AM] Scott Queen
event: 'bf_benefit_click', -> event: 'bf-accordion-open',
[10:52 AM] Scott Queen
for the other event associate with accordions, the link click, event: 'bf_benefit_link', - can you confirm that we are keeping that the same?
[10:53 AM] Nick Pistone
Yeah I’m good with bf-benefit-link
[10:54 AM] Nick Pistone
Did you want to use underscores or hyphens?
[10:57 AM] Scott Queen
ah - good catch
[10:57 AM] Scott Queen
Google recomends underscores
[10:57 AM] Scott Queen
I'll update
[10:59 AM] Scott Queen
let me clarify, underscores for events - it doesn't give guidance for other data value structures
[11:02 AM] Nick Pistone
yeah we use underscores for the event names
[11:02 AM] Nick Pistone
so I think it's ok to have hyphens for the data layer values
[11:02 AM] Nick Pistone
especially since we already have them like that
 like 1
[11:03 AM] Nick Pistone
the event name is assigned in GTM and then passes to GA from there. So that's the step where we need to align with Google standards. But it's good to be thinking about it throughout

**Comment by nickpistone** [comment]
Confirmed
