### ISSUE TITLE
Error message not working on date fieldsets with out required flag

### ISSUE THREAD

**Issue by diegocob** [GSA/px-benefit-finder#1737]
### What's expected

While testing the [all-benefits form](https://cms.usa.gov/benefit-finder/all-benefits) in Prod, I noticed that when entering an incorrect year `234` the error message did not come up. Is this bc the question is not required? 

### What happened

As a user, error message should come up if I enter an incorrect year.

![Image](https://github.com/user-attachments/assets/4dd9d4b4-b249-4767-a648-8b8ffff08fb6)

### How to replicate

There should be an error message when I enter the wrong year on DOB or DOD (that is not a required question) in the all-benefits form.

**Comment by scottqueen-bixal** [comment]
Getting the validation requirement removed is a low  level of effort, but we don't currently have a way to clear an assignment of value to month once it is selected.  

Here is a use case
> As a user, when I provide invalid values to inputs, I should be able to clear alerts by removing values for those fieldsets and proceed if they are not required

Because we want to alert users to invalid date inputs even when they are not required means we need to be able to "clear" the answers, for radios, selects, and inputs.
