### ISSUE TITLE
Refactor | Remove Lint Staged

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-benefit-finder#1956]
### Description

if we are no longer using lint staged, and are leveraging githooks to handle the same functionality, let's remove it

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Removed lint-staged from package.json and .lintstagedrc file. Updated pre-commit hook to handle linting directly.

You can review changes in this commit: https://github.com/lattaai13/GSA-px-benefit-finder-1956/commit/fba82e82fb289039da7e693ae73b123f39215446.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by scottqueen-bixal** [comment]
this is still in use
