### ISSUE TITLE
ICONs | Results Page Sharing Icons

### ISSUE THREAD

**Issue by fongcindy** [GSA/px-benefit-finder#908]
### Description

On the results page under the **Sharing** section, we have "Share results" and "Email results" text only. We would like to add icons in the button/CTA as well. 
![image](https://github.com/GSA/px-benefit-finder/assets/128498116/9b42ea66-ff6c-48c1-bdf7-156063042f32)

### User Story

As a user, I would like to see the icons inside the share and email results button.

**Comment by ErnestoFernandezAlvarez** [comment]
Hello @fongcindy @scottqueen-bixal 

Here are my comments about the Button Icons for this section. Note the image at the top with the buttons stacked is from the design file and the bottom one with aligned buttons is the MVP.

- I used "Share results" instead of "Share link" (this might have been changed by Content during the MVP QA. Please follow Content direction on this.
-The design file has the buttons stacked while MVP has them arranged horizontally. 

https://www.figma.com/file/y8Op8kBqkvCEMZQ7i13Fcr/SHARED-DOC-BEARS?type=design&node-id=2205%3A35599&mode=design&t=7EmVAg7OpmgYvJBc-1

<img width="1027" alt="Screenshot 2024-03-07 at 1 24 52 PM" src="https://github.com/GSA/px-benefit-finder/assets/125310691/601d19bf-f6e2-45d3-9a3f-e62a8555a161">

**Comment by angelina-smith** [comment]
@scottqueen-bixal These icons are being announced as expected by NVDA and JAWS in Storybook.
